name: Build and Test Run on Windows

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install build dependencies
      run: |
        # Install NASM and pkg-config for FFmpeg compilation
        choco install nasm pkgconfiglite
        # Install FFmpeg development libraries
        choco install ffmpeg --params "'/InstallDir:C:\ffmpeg'"
        # Add to PATH
        echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\ffmpeg\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build with static FFmpeg
      run: cargo build
      env:
        # Use system FFmpeg with pkg-config
        PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
        PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1
        PKG_CONFIG_PATH: "C:\\ffmpeg\\lib\\pkgconfig"
    
    - name: Test Run (with timeout)
      run: |
        # Run the binary with a 30 second timeout
        timeout 30 cargo run
      continue-on-error: true