name: Build and Test Run on Linux

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Install build dependencies for static FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          build-essential \
          yasm \
          nasm \
          cmake \
          pkg-config
    
    - name: Build with static FFmpeg
      run: cargo build
      env:
        # Force static linking - builds FFmpeg from source
        FFMPEG_SYS_STATIC: 1
    
    - name: Test Run (with virtual display)
      run: |
        # Run with virtual display and 30 second timeout
        xvfb-run -a timeout 30 cargo run
      continue-on-error: true