name: Build and Test Run on Linux

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download FFmpeg
        run: |
          curl -L -o ffmpeg-release.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
          mkdir ffmpeg
          tar -xf ffmpeg-release.tar.xz -C ffmpeg --strip-components=1

      - name: Set FFMPEG_DIR and PATH
        run: |
          echo "FFMPEG_DIR=${{ github.workspace }}/ffmpeg" >> $GITHUB_ENV
          echo "${{ github.workspace }}/ffmpeg" >> $GITHUB_PATH

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build

      - name: Run for at least 30 seconds
        run: |
          cargo run &
          sleep 30
