name: Build and Test Run on Windows

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-and-run:
    if: github.repository == 'reim-developer/boquilahub'
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download FFmpeg
        run: |
          curl -L -o ffmpeg.7z https://github.com/GyanD/codexffmpeg/releases/download/7.1.1/ffmpeg-7.1.1-full_build-shared.7z
          7z x ffmpeg.7z -offmpeg -y

      - name: Set FFMPEG_DIR and PATH
        run: |
          echo "FFMPEG_DIR=${{ github.workspace }}\ffmpeg\ffmpeg-7.1.1-full_build-shared" >> $env:GITHUB_ENV
          echo "${{ github.workspace }}\ffmpeg\ffmpeg-7.1.1-full_build-shared\bin" >> $env:GITHUB_PATH

      - name: Install Rust (if needed)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build

      - name: Run for at least 30 seconds
        run: |
          Start-Process -NoNewWindow -FilePath cargo -ArgumentList "run" 
          Start-Sleep -Seconds 30
