name: Build and Test Run on Windows

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: |
        choco install nasm pkgconfiglite 7zip

    - name: Download and extract FFmpeg dev build
      run: |
        curl -LO https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z
        7z x ffmpeg-git-full.7z -offmpeg
        $ffmpegDir = Get-ChildItem .\ffmpeg | Where-Object { $_.PSIsContainer } | Select-Object -First 1
        Move-Item ".\ffmpeg\$($ffmpegDir.Name)" "C:\ffmpeg"
        echo "C:\ffmpeg\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "PKG_CONFIG_PATH=C:\ffmpeg\lib\pkgconfig" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build with static FFmpeg
      run: cargo build
      env:
        PKG_CONFIG_ALLOW_SYSTEM_LIBS: 1
        PKG_CONFIG_ALLOW_SYSTEM_CFLAGS: 1

    - name: Test Run (with timeout)
      run: |
        timeout 30 cargo run
      continue-on-error: true
