name: Build and Test Run on Linux

on:
  push:
   branches: ["main"]

  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install FFmpeg
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ffmpeg \
            libavutil-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libavdevice-dev \
            libavfilter-dev \
            libswresample-dev
            
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build

      - name: Run for at least 30 seconds
        run: |
          cargo run &
          sleep 30
