name: Build and Test Run on Windows

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build
    
    - name: Test Run (with timeout)
      run: |
        # Run the binary with a 30 second timeout
        timeout 30 cargo run
      continue-on-error: true